"""volunteer_records: semester

Revision ID: 05f995791907
Revises: 9927d86dfce2
Create Date: 2026-09-05 15:50:38.623986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05f995791907'
down_revision: Union[str, Sequence[str], None] = '9927d86dfce2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volunteer_records', sa.Column('semester', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('volunteer_records', 'semester')
    # ### end Alembic commands ###
