"""add education policy catalog

Revision ID: 0f4ea388bc69
Revises: f6a9c3d5e702
Create Date: 2026-09-08 18:50:34.388841

"""
from datetime import UTC, date, datetime
from typing import Sequence, Union
from uuid import UUID

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f4ea388bc69'
down_revision: Union[str, Sequence[str], None] = 'f6a9c3d5e702'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


POLICY_2015_ID = UUID("873c56d6-0f2b-4b42-a9c5-4e0f21e9e101")
POLICY_2022_ID = UUID("873c56d6-0f2b-4b42-a9c5-4e0f21e9e202")
VERIFIED_AT = datetime(2026, 9, 8, tzinfo=UTC)
STUDENT_RECORD_GUIDE_URL = "https://star.moe.go.kr/web/contents/m10100.do"
CURRICULUM_NOTICE_URL = (
    "https://www.moe.go.kr/boardCnts/viewRenew.do?boardID=141&boardSeq=93458"
    "&lev=0&m=0404&opType=N&s=moe&statusYN=W"
)
ADMISSION_BASICS_URL = "https://www.adiga.kr/uct/ces/archiveView.do?menuId=PCUCTCES1000&prtlBbsId=25989"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('freshman_year_start', sa.Integer(), nullable=False),
    sa.Column('freshman_year_end', sa.Integer(), nullable=True),
    sa.Column('curriculum_name', sa.String(length=160), nullable=False),
    sa.Column('rank_grade_scale', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_label', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_published_on', sa.Date(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_education_policies_code'), 'education_policies', ['code'], unique=True)
    op.create_index(op.f('ix_education_policies_freshman_year_end'), 'education_policies', ['freshman_year_end'], unique=False)
    op.create_index(op.f('ix_education_policies_freshman_year_start'), 'education_policies', ['freshman_year_start'], unique=False)
    op.create_table('admission_policy_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=True),
    sa.Column('admission_year_start', sa.Integer(), nullable=True),
    sa.Column('admission_year_end', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('decision_scope', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('action_required', sa.Text(), nullable=True),
    sa.Column('source_label', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_published_on', sa.Date(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['education_policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admission_policy_rules_admission_year_end'), 'admission_policy_rules', ['admission_year_end'], unique=False)
    op.create_index(op.f('ix_admission_policy_rules_admission_year_start'), 'admission_policy_rules', ['admission_year_start'], unique=False)
    op.create_index(op.f('ix_admission_policy_rules_category'), 'admission_policy_rules', ['category'], unique=False)
    op.create_index(op.f('ix_admission_policy_rules_code'), 'admission_policy_rules', ['code'], unique=True)
    op.create_index(op.f('ix_admission_policy_rules_policy_id'), 'admission_policy_rules', ['policy_id'], unique=False)
    # ### end Alembic commands ###

    # 법령·공식 지침은 서비스 문구가 아니라 별도 기준 데이터로 넣는다. 새 자료가
    # 나오면 이 행을 덮어쓰지 않고 다음 적용 구간/출처를 추가해야 과거 학생의
    # 판정 근거가 사라지지 않는다.
    policies = sa.table(
        "education_policies",
        sa.column("id", sa.UUID()),
        sa.column("code", sa.String()),
        sa.column("title", sa.String()),
        sa.column("freshman_year_start", sa.Integer()),
        sa.column("freshman_year_end", sa.Integer()),
        sa.column("curriculum_name", sa.String()),
        sa.column("rank_grade_scale", sa.Integer()),
        sa.column("summary", sa.Text()),
        sa.column("details", postgresql.JSONB()),
        sa.column("source_label", sa.String()),
        sa.column("source_url", sa.Text()),
        sa.column("source_published_on", sa.Date()),
        sa.column("verified_at", sa.DateTime(timezone=True)),
    )
    op.bulk_insert(
        policies,
        [
            {
                "id": POLICY_2015_ID,
                "code": "2015-revised-high-school",
                "title": "2015 개정 교육과정 고교생 기준",
                "freshman_year_start": 2018,
                "freshman_year_end": 2024,
                "curriculum_name": "2015 개정 교육과정",
                "rank_grade_scale": 9,
                "summary": "2015 개정 교육과정 적용 학생의 석차등급은 9등급 체계로 관리합니다.",
                "details": {
                    "grade_system": "석차등급 9등급 산출",
                    "student_record": "학년별 교육과정과 과목별 학생부 기재 기준을 적용합니다.",
                    "service_handling": "성적 입력·평균·분포는 1~9등급 범위에서만 계산합니다.",
                },
                "source_label": "학교생활기록부 종합지원포털 · 2015 개정 교육과정 평가 기준",
                "source_url": STUDENT_RECORD_GUIDE_URL,
                "source_published_on": None,
                "verified_at": VERIFIED_AT,
            },
            {
                "id": POLICY_2022_ID,
                "code": "2022-revised-high-school",
                "title": "2022 개정 교육과정·고교학점제 기준",
                "freshman_year_start": 2025,
                "freshman_year_end": None,
                "curriculum_name": "2022 개정 교육과정",
                "rank_grade_scale": 5,
                "summary": "2025학년도 고1부터 적용된 2022 개정 교육과정·고교학점제 기준으로 석차등급은 5등급 체계입니다.",
                "details": {
                    "grade_system": "석차등급 5등급 산출",
                    "student_record": "교과는 학기별로 운영되며, 과목별 평가·성취도 기준을 함께 확인합니다.",
                    "admission_context": "2025학년도 고1은 2028학년도 대입 제도 개편 적용 대상입니다.",
                    "service_handling": "성적 입력·평균·분포는 1~5등급 범위에서만 계산합니다.",
                },
                "source_label": "교육부 2022 개정 교육과정 고시 및 학교생활기록부 종합지원포털",
                "source_url": CURRICULUM_NOTICE_URL,
                "source_published_on": date(2022, 12, 22),
                "verified_at": VERIFIED_AT,
            },
        ],
    )

    rules = sa.table(
        "admission_policy_rules",
        sa.column("id", sa.UUID()),
        sa.column("code", sa.String()),
        sa.column("policy_id", sa.UUID()),
        sa.column("admission_year_start", sa.Integer()),
        sa.column("admission_year_end", sa.Integer()),
        sa.column("category", sa.String()),
        sa.column("decision_scope", sa.String()),
        sa.column("title", sa.String()),
        sa.column("summary", sa.Text()),
        sa.column("action_required", sa.Text()),
        sa.column("source_label", sa.String()),
        sa.column("source_url", sa.Text()),
        sa.column("source_published_on", sa.Date()),
        sa.column("verified_at", sa.DateTime(timezone=True)),
    )
    op.bulk_insert(
        rules,
        [
            {
                "id": UUID("d9c0fc4d-fbd9-4fb2-8b57-2f3913aa7101"),
                "code": "rank-scale-2015-revised",
                "policy_id": POLICY_2015_ID,
                "admission_year_start": None,
                "admission_year_end": None,
                "category": "student_record",
                "decision_scope": "common",
                "title": "석차등급 9등급제",
                "summary": "2015 개정 교육과정 적용 학생의 석차등급은 9등급 체계로 산출됩니다.",
                "action_required": "지원 전형의 학생부 반영 방식은 대학·전형별 모집요강에서 별도로 확인합니다.",
                "source_label": "학교생활기록부 종합지원포털",
                "source_url": STUDENT_RECORD_GUIDE_URL,
                "source_published_on": None,
                "verified_at": VERIFIED_AT,
            },
            {
                "id": UUID("d9c0fc4d-fbd9-4fb2-8b57-2f3913aa7202"),
                "code": "rank-scale-2022-revised",
                "policy_id": POLICY_2022_ID,
                "admission_year_start": 2028,
                "admission_year_end": None,
                "category": "student_record",
                "decision_scope": "common",
                "title": "석차등급 5등급제",
                "summary": "2022 개정 교육과정 적용 학년의 석차등급은 5등급 체계로 산출됩니다.",
                "action_required": "과목별 성취도와 석차등급 제공 여부는 학생부 원문을 함께 확인합니다.",
                "source_label": "학교생활기록부 종합지원포털",
                "source_url": STUDENT_RECORD_GUIDE_URL,
                "source_published_on": None,
                "verified_at": VERIFIED_AT,
            },
            {
                "id": UUID("d9c0fc4d-fbd9-4fb2-8b57-2f3913aa7208"),
                "code": "2028-admission-framework",
                "policy_id": POLICY_2022_ID,
                "admission_year_start": 2028,
                "admission_year_end": 2028,
                "category": "admission_framework",
                "decision_scope": "common",
                "title": "2028학년도 대입 제도 적용",
                "summary": "2025학년도 고1 학생은 2028학년도 대입 제도 개편과 2022 개정 교육과정이 적용되는 환경에서 대입을 준비합니다.",
                "action_required": "지원 희망 대학의 2028학년도 모집요강이 공고되면 시행계획과 달라진 내용을 다시 대조합니다.",
                "source_label": "교육부 · 2028 대입 주요 사항 안내",
                "source_url": "https://www.moe.go.kr/boardCnts/viewRenew.do?boardID=294&boardSeq=104960&lev=0&m=020402&opType=N&page=1&s=moe&searchType=null&statusYN=W",
                "source_published_on": date(2025, 12, 22),
                "verified_at": VERIFIED_AT,
            },
            {
                "id": UUID("d9c0fc4d-fbd9-4fb2-8b57-2f3913aa7286"),
                "code": "susi-six-application-limit-2028",
                "policy_id": None,
                "admission_year_start": 2028,
                "admission_year_end": 2028,
                "category": "application_limit",
                "decision_scope": "common",
                "title": "수시 지원 횟수 제한",
                "summary": "수시모집 전형의 지원 가능 횟수는 원칙적으로 최대 6회이며, 예외 대상 대학·전형은 공식 기본사항을 따릅니다.",
                "action_required": "지원 카드를 확정하기 전 특별법 대학·전문대 등 예외와 각 전형의 지원 횟수를 함께 점검합니다.",
                "source_label": "대입정보포털 · 2028학년도 대학입학전형기본사항",
                "source_url": ADMISSION_BASICS_URL,
                "source_published_on": None,
                "verified_at": VERIFIED_AT,
            },
            {
                "id": UUID("d9c0fc4d-fbd9-4fb2-8b57-2f3913aa7299"),
                "code": "graduate-susi-eligibility-is-track-specific",
                "policy_id": None,
                "admission_year_start": 2028,
                "admission_year_end": 2028,
                "category": "eligibility",
                "decision_scope": "track_specific",
                "title": "졸업생·재수생 수시 지원 자격",
                "summary": "9등급제 또는 5등급제 여부만으로 수시 재지원 가능 여부를 판단하지 않습니다. 지원 자격은 대학·모집단위·전형별 모집요강의 졸업자·졸업예정자·추천·지역 요건으로 판정합니다.",
                "action_required": "지원처를 고르면 해당 전형의 공식 지원 자격을 수집·표시한 뒤에만 가능 여부를 안내합니다.",
                "source_label": "대입정보포털 · 2028학년도 대학입학전형기본사항",
                "source_url": ADMISSION_BASICS_URL,
                "source_published_on": None,
                "verified_at": VERIFIED_AT,
            },
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admission_policy_rules_policy_id'), table_name='admission_policy_rules')
    op.drop_index(op.f('ix_admission_policy_rules_code'), table_name='admission_policy_rules')
    op.drop_index(op.f('ix_admission_policy_rules_category'), table_name='admission_policy_rules')
    op.drop_index(op.f('ix_admission_policy_rules_admission_year_start'), table_name='admission_policy_rules')
    op.drop_index(op.f('ix_admission_policy_rules_admission_year_end'), table_name='admission_policy_rules')
    op.drop_table('admission_policy_rules')
    op.drop_index(op.f('ix_education_policies_freshman_year_start'), table_name='education_policies')
    op.drop_index(op.f('ix_education_policies_freshman_year_end'), table_name='education_policies')
    op.drop_index(op.f('ix_education_policies_code'), table_name='education_policies')
    op.drop_table('education_policies')
    # ### end Alembic commands ###
