"""roadmap plan event order index

Revision ID: 1a5d54f88842
Revises: 6cc1e80ff698
Create Date: 2026-09-04 03:33:15.689874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a5d54f88842'
down_revision: Union[str, Sequence[str], None] = '6cc1e80ff698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 기존 행이 있는 테이블에 NOT NULL 컬럼을 그냥 붙이면 NotNullViolation이 난다.
    # 서버 기본값으로 기존 행을 채운 뒤 기본값을 떼어, 앞으로는 모델의 값이 쓰이게 한다.
    op.add_column(
        'roadmap_plan_events',
        sa.Column('order_index', sa.Integer(), nullable=False, server_default='0'),
    )
    op.alter_column('roadmap_plan_events', 'order_index', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roadmap_plan_events', 'order_index')
    # ### end Alembic commands ###
