"""add fit_score, SWOT expansion, activity inventory, knowledge graph

Revision ID: 2c28ba5a96d5
Revises: 51d1a3c8b62a
Create Date: 2026-08-31 21:44:29.866126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c28ba5a96d5'
down_revision: Union[str, Sequence[str], None] = '51d1a3c8b62a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagnoses', sa.Column('activity_inventory', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('diagnoses', sa.Column('knowledge_graph_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('diagnoses', sa.Column('opportunities', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('diagnoses', sa.Column('threats', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('diagnoses', sa.Column('fit_score', sa.Integer(), nullable=True))
    op.add_column('diagnoses', sa.Column('headline_comment', sa.Text(), nullable=True))
    op.drop_column('diagnoses', 'unrecorded_points')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagnoses', sa.Column('unrecorded_points', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('diagnoses', 'headline_comment')
    op.drop_column('diagnoses', 'fit_score')
    op.drop_column('diagnoses', 'threats')
    op.drop_column('diagnoses', 'opportunities')
    op.drop_column('diagnoses', 'knowledge_graph_links')
    op.drop_column('diagnoses', 'activity_inventory')
    # ### end Alembic commands ###
