"""link plan items to roadmap nodes and plan events

Revision ID: 48774339b4cf
Revises: ef28cddc0af0
Create Date: 2026-09-04 11:39:48.947220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48774339b4cf'
down_revision: Union[str, Sequence[str], None] = 'ef28cddc0af0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan_items', sa.Column('roadmap_node_id', sa.UUID(), nullable=True))
    op.add_column('plan_items', sa.Column('source_plan_event_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'fk_plan_items_roadmap_node', 'plan_items', 'roadmap_nodes',
        ['roadmap_node_id'], ['id'], ondelete='SET NULL',
    )
    op.create_foreign_key(
        'fk_plan_items_source_plan_event', 'plan_items', 'roadmap_plan_events',
        ['source_plan_event_id'], ['id'], ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_plan_items_source_plan_event', 'plan_items', type_='foreignkey')
    op.drop_constraint('fk_plan_items_roadmap_node', 'plan_items', type_='foreignkey')
    op.drop_column('plan_items', 'source_plan_event_id')
    op.drop_column('plan_items', 'roadmap_node_id')
    # ### end Alembic commands ###
