"""restructure diagnoses into sections

Revision ID: 51d1a3c8b62a
Revises: b9c56ced77ac
Create Date: 2026-08-30 17:53:46.328892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51d1a3c8b62a'
down_revision: Union[str, Sequence[str], None] = 'b9c56ced77ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagnoses', sa.Column('grades_trend', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('diagnoses', sa.Column('semester_reviews', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('diagnoses', sa.Column('unrecorded_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('diagnoses', 'overall_summary')
    op.drop_column('diagnoses', 'domain_feedback')
    op.drop_column('diagnoses', 'narrative_report')
    op.drop_column('diagnoses', 'keyword_map')
    op.drop_column('diagnoses', 'career_gap_analysis')
    op.drop_column('diagnoses', 'semester_summaries')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagnoses', sa.Column('semester_summaries', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('diagnoses', sa.Column('career_gap_analysis', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('diagnoses', sa.Column('keyword_map', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('diagnoses', sa.Column('narrative_report', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('diagnoses', sa.Column('domain_feedback', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('diagnoses', sa.Column('overall_summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('diagnoses', 'unrecorded_points')
    op.drop_column('diagnoses', 'semester_reviews')
    op.drop_column('diagnoses', 'grades_trend')
    # ### end Alembic commands ###
