"""awards: grade, semester, participants

Revision ID: 5adf05979741
Revises: c91cd010da60
Create Date: 2026-09-04 21:55:10.288113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5adf05979741'
down_revision: Union[str, Sequence[str], None] = 'c91cd010da60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('awards', sa.Column('grade', sa.Integer(), nullable=True))
    op.add_column('awards', sa.Column('semester', sa.Integer(), nullable=True))
    op.add_column('awards', sa.Column('participants', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('awards', 'participants')
    op.drop_column('awards', 'semester')
    op.drop_column('awards', 'grade')
    # ### end Alembic commands ###
