"""add auth rate limit events table

Revision ID: 5db44b9e5ca7
Revises: a5142712af42
Create Date: 2026-09-14 22:47:34.718106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5db44b9e5ca7'
down_revision: Union[str, Sequence[str], None] = 'a5142712af42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_rate_limit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_auth_rate_limit_key_action_created', 'auth_rate_limit_events', ['key', 'action', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_auth_rate_limit_key_action_created', table_name='auth_rate_limit_events')
    op.drop_table('auth_rate_limit_events')
    # ### end Alembic commands ###
