"""roadmap, activity thread, reconciliation, attachments, feedback, upload originals

Revision ID: 628a2bdcb202
Revises: acee8bdbf5c5
Create Date: 2026-09-04 03:24:17.171655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '628a2bdcb202'
down_revision: Union[str, Sequence[str], None] = 'acee8bdbf5c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_threads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_threads_user_id'), 'activity_threads', ['user_id'], unique=False)
    op.create_index('ix_activity_threads_user_status', 'activity_threads', ['user_id', 'status'], unique=False)
    op.create_table('roadmaps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('career_track', sa.String(length=255), nullable=False),
    sa.Column('template_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmaps_user_id'), 'roadmaps', ['user_id'], unique=False)
    op.create_index('ix_roadmaps_user_status', 'roadmaps', ['user_id', 'status'], unique=False)
    op.create_table('activity_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_activity_attachments_activity', 'activity_attachments', ['activity_id'], unique=False)
    op.create_index(op.f('ix_activity_attachments_user_id'), 'activity_attachments', ['user_id'], unique=False)
    op.create_table('roadmap_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('roadmap_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('narrative_stage', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('candidate_subjects', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('competency_goals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('instantiated_activity_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instantiated_activity_id'], ['activities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_roadmap_nodes_roadmap_order', 'roadmap_nodes', ['roadmap_id', 'order_index'], unique=False)
    op.create_index(op.f('ix_roadmap_nodes_user_id'), 'roadmap_nodes', ['user_id'], unique=False)
    op.create_index('ix_roadmap_nodes_user_period', 'roadmap_nodes', ['user_id', 'grade', 'semester'], unique=False)
    op.create_table('recommendation_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('option_index', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recommendation_feedback_user_created', 'recommendation_feedback', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_recommendation_feedback_user_id'), 'recommendation_feedback', ['user_id'], unique=False)
    op.create_table('reconciliation_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=True),
    sa.Column('roadmap_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=True),
    sa.Column('match_type', sa.String(length=20), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['roadmap_nodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reconciliation_logs_user_created', 'reconciliation_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_reconciliation_logs_user_id'), 'reconciliation_logs', ['user_id'], unique=False)
    op.create_table('roadmap_plan_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('roadmap_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('month_day', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['roadmap_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_roadmap_plan_events_node', 'roadmap_plan_events', ['node_id'], unique=False)
    op.create_index(op.f('ix_roadmap_plan_events_user_id'), 'roadmap_plan_events', ['user_id'], unique=False)
    op.add_column('academic_performance', sa.Column('roadmap_node_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'fk_academic_performance_roadmap_node', 'academic_performance', 'roadmap_nodes',
        ['roadmap_node_id'], ['id'], ondelete='SET NULL',
    )
    op.add_column('activities', sa.Column('thread_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'fk_activities_thread', 'activities', 'activity_threads',
        ['thread_id'], ['id'], ondelete='SET NULL',
    )
    op.add_column('seteuk_uploads', sa.Column('file_name', sa.String(length=255), nullable=True))
    op.add_column('seteuk_uploads', sa.Column('content_type', sa.String(length=100), nullable=True))
    op.add_column('seteuk_uploads', sa.Column('size_bytes', sa.Integer(), nullable=True))
    op.add_column('seteuk_uploads', sa.Column('content', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seteuk_uploads', 'content')
    op.drop_column('seteuk_uploads', 'size_bytes')
    op.drop_column('seteuk_uploads', 'content_type')
    op.drop_column('seteuk_uploads', 'file_name')
    op.drop_constraint('fk_activities_thread', 'activities', type_='foreignkey')
    op.drop_column('activities', 'thread_id')
    op.drop_constraint('fk_academic_performance_roadmap_node', 'academic_performance', type_='foreignkey')
    op.drop_column('academic_performance', 'roadmap_node_id')
    op.drop_index(op.f('ix_roadmap_plan_events_user_id'), table_name='roadmap_plan_events')
    op.drop_index('ix_roadmap_plan_events_node', table_name='roadmap_plan_events')
    op.drop_table('roadmap_plan_events')
    op.drop_index(op.f('ix_reconciliation_logs_user_id'), table_name='reconciliation_logs')
    op.drop_index('ix_reconciliation_logs_user_created', table_name='reconciliation_logs')
    op.drop_table('reconciliation_logs')
    op.drop_index(op.f('ix_recommendation_feedback_user_id'), table_name='recommendation_feedback')
    op.drop_index('ix_recommendation_feedback_user_created', table_name='recommendation_feedback')
    op.drop_table('recommendation_feedback')
    op.drop_index('ix_roadmap_nodes_user_period', table_name='roadmap_nodes')
    op.drop_index(op.f('ix_roadmap_nodes_user_id'), table_name='roadmap_nodes')
    op.drop_index('ix_roadmap_nodes_roadmap_order', table_name='roadmap_nodes')
    op.drop_table('roadmap_nodes')
    op.drop_index(op.f('ix_activity_attachments_user_id'), table_name='activity_attachments')
    op.drop_index('ix_activity_attachments_activity', table_name='activity_attachments')
    op.drop_table('activity_attachments')
    op.drop_index('ix_roadmaps_user_status', table_name='roadmaps')
    op.drop_index(op.f('ix_roadmaps_user_id'), table_name='roadmaps')
    op.drop_table('roadmaps')
    op.drop_index('ix_activity_threads_user_status', table_name='activity_threads')
    op.drop_index(op.f('ix_activity_threads_user_id'), table_name='activity_threads')
    op.drop_table('activity_threads')
    # ### end Alembic commands ###
