"""add student_interests, diagnoses, users profile fields

Revision ID: 688c346a8a94
Revises: ae70a0089675
Create Date: 2026-08-27 11:24:47.539916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '688c346a8a94'
down_revision: Union[str, Sequence[str], None] = 'ae70a0089675'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnoses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('failure_reason', sa.String(length=1000), nullable=True),
    sa.Column('semester_summaries', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('domain_feedback', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('career_thread', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('overall_summary', sa.Text(), nullable=True),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('weaknesses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('career_gap_analysis', sa.Text(), nullable=True),
    sa.Column('keyword_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnoses_created_at'), 'diagnoses', ['created_at'], unique=False)
    op.create_index(op.f('ix_diagnoses_user_id'), 'diagnoses', ['user_id'], unique=False)
    op.create_table('student_interests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('field_key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_interests_answered_at'), 'student_interests', ['answered_at'], unique=False)
    op.create_index(op.f('ix_student_interests_field_key'), 'student_interests', ['field_key'], unique=False)
    op.create_index('ix_student_interests_user_field_answered', 'student_interests', ['user_id', 'field_key', 'answered_at'], unique=False)
    op.create_index(op.f('ix_student_interests_user_id'), 'student_interests', ['user_id'], unique=False)
    op.add_column('users', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('current_grade', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('current_semester', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'current_semester')
    op.drop_column('users', 'current_grade')
    op.drop_column('users', 'name')
    op.drop_index(op.f('ix_student_interests_user_id'), table_name='student_interests')
    op.drop_index('ix_student_interests_user_field_answered', table_name='student_interests')
    op.drop_index(op.f('ix_student_interests_field_key'), table_name='student_interests')
    op.drop_index(op.f('ix_student_interests_answered_at'), table_name='student_interests')
    op.drop_table('student_interests')
    op.drop_index(op.f('ix_diagnoses_user_id'), table_name='diagnoses')
    op.drop_index(op.f('ix_diagnoses_created_at'), table_name='diagnoses')
    op.drop_table('diagnoses')
    # ### end Alembic commands ###
