"""roadmap plan event priority and description

Revision ID: 6cc1e80ff698
Revises: 628a2bdcb202
Create Date: 2026-09-04 03:27:32.323184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cc1e80ff698'
down_revision: Union[str, Sequence[str], None] = '628a2bdcb202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roadmap_plan_events', sa.Column('priority', sa.String(length=20), nullable=False))
    op.add_column('roadmap_plan_events', sa.Column('description', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roadmap_plan_events', 'description')
    op.drop_column('roadmap_plan_events', 'priority')
    # ### end Alembic commands ###
