"""seteuk upload imported at

Revision ID: 88b5b06922e6
Revises: 48774339b4cf
Create Date: 2026-09-04 11:49:52.619234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88b5b06922e6'
down_revision: Union[str, Sequence[str], None] = '48774339b4cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seteuk_uploads', sa.Column('imported_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seteuk_uploads', 'imported_at')
    # ### end Alembic commands ###
