"""add admission catalog tables

Revision ID: 8cb274a175f9
Revises: 9927d86dfce2
Create Date: 2026-09-06 18:06:17.937806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cb274a175f9'
down_revision: Union[str, Sequence[str], None] = '9927d86dfce2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('universities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('official_code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('campus_name', sa.String(length=120), nullable=True),
    sa.Column('region', sa.String(length=80), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_universities_name'), 'universities', ['name'], unique=False)
    op.create_index(op.f('ix_universities_official_code'), 'universities', ['official_code'], unique=True)
    op.create_table('admission_programs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('university_id', sa.UUID(), nullable=False),
    sa.Column('admission_year', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('college_name', sa.String(length=160), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_status', sa.String(length=20), nullable=False),
    sa.Column('is_recruiting', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('university_id', 'admission_year', 'name', name='uq_admission_program_year')
    )
    op.create_index(op.f('ix_admission_programs_admission_year'), 'admission_programs', ['admission_year'], unique=False)
    op.create_index(op.f('ix_admission_programs_name'), 'admission_programs', ['name'], unique=False)
    op.create_index(op.f('ix_admission_programs_university_id'), 'admission_programs', ['university_id'], unique=False)
    op.create_table('admission_tracks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('admission_type', sa.String(length=80), nullable=True),
    sa.Column('recruitment_period', sa.String(length=40), nullable=True),
    sa.Column('has_document_review', sa.Boolean(), nullable=True),
    sa.Column('has_interview', sa.Boolean(), nullable=True),
    sa.Column('has_minimum_requirement', sa.Boolean(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_status', sa.String(length=20), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['admission_programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id', 'name', name='uq_admission_track_program')
    )
    op.create_index(op.f('ix_admission_tracks_program_id'), 'admission_tracks', ['program_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admission_tracks_program_id'), table_name='admission_tracks')
    op.drop_table('admission_tracks')
    op.drop_index(op.f('ix_admission_programs_university_id'), table_name='admission_programs')
    op.drop_index(op.f('ix_admission_programs_name'), table_name='admission_programs')
    op.drop_index(op.f('ix_admission_programs_admission_year'), table_name='admission_programs')
    op.drop_table('admission_programs')
    op.drop_index(op.f('ix_universities_official_code'), table_name='universities')
    op.drop_index(op.f('ix_universities_name'), table_name='universities')
    op.drop_table('universities')
    # ### end Alembic commands ###
