"""users: freshman_academic_year

Revision ID: 9927d86dfce2
Revises: 5adf05979741
Create Date: 2026-09-05 15:16:53.053551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9927d86dfce2'
down_revision: Union[str, Sequence[str], None] = '5adf05979741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('freshman_academic_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'freshman_academic_year')
    # ### end Alembic commands ###
