"""consultation_sessions: new table; conversations: purpose column

Revision ID: a4d0ac2855b5
Revises: 05f995791907
Create Date: 2026-09-06 01:56:58.562525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a4d0ac2855b5'
down_revision: Union[str, Sequence[str], None] = '05f995791907'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultation_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('target_grade', sa.Integer(), nullable=False),
    sa.Column('target_semester', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ready_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('concluded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('full_replan_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('draft_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id')
    )
    op.create_index(op.f('ix_consultation_sessions_user_id'), 'consultation_sessions', ['user_id'], unique=False)
    op.create_index('ix_consultation_sessions_user_period', 'consultation_sessions', ['user_id', 'kind', 'target_grade', 'target_semester'], unique=False)
    op.create_index('ix_consultation_sessions_user_status', 'consultation_sessions', ['user_id', 'status'], unique=False)
    op.add_column(
        'conversations',
        sa.Column('purpose', sa.String(length=40), nullable=False, server_default='general'),
    )
    op.alter_column('conversations', 'purpose', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'purpose')
    op.drop_index('ix_consultation_sessions_user_status', table_name='consultation_sessions')
    op.drop_index('ix_consultation_sessions_user_period', table_name='consultation_sessions')
    op.drop_index(op.f('ix_consultation_sessions_user_id'), table_name='consultation_sessions')
    op.drop_table('consultation_sessions')
    # ### end Alembic commands ###
