"""auth hardening: google login, email verification, password reset, account withdrawal, cascade user deletes

Revision ID: a5142712af42
Revises: 0f4ea388bc69
Create Date: 2026-09-14 22:45:15.275428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5142712af42'
down_revision: Union[str, Sequence[str], None] = '0f4ea388bc69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verification_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verification_tokens_token_hash'), 'email_verification_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_email_verification_tokens_user_id'), 'email_verification_tokens', ['user_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.drop_constraint(op.f('academic_performance_user_id_fkey'), 'academic_performance', type_='foreignkey')
    op.create_foreign_key(None, 'academic_performance', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('activities_user_id_fkey'), 'activities', type_='foreignkey')
    op.create_foreign_key(None, 'activities', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('activity_attachments_user_id_fkey'), 'activity_attachments', type_='foreignkey')
    op.create_foreign_key(None, 'activity_attachments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('activity_reviews_user_id_fkey'), 'activity_reviews', type_='foreignkey')
    op.create_foreign_key(None, 'activity_reviews', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('activity_threads_user_id_fkey'), 'activity_threads', type_='foreignkey')
    op.create_foreign_key(None, 'activity_threads', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('attendance_user_id_fkey'), 'attendance', type_='foreignkey')
    op.create_foreign_key(None, 'attendance', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('awards_user_id_fkey'), 'awards', type_='foreignkey')
    op.create_foreign_key(None, 'awards', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('consultation_sessions_user_id_fkey'), 'consultation_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'consultation_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('conversations_user_id_fkey'), 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('diagnoses_user_id_fkey'), 'diagnoses', type_='foreignkey')
    op.create_foreign_key(None, 'diagnoses', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('plan_items_user_id_fkey'), 'plan_items', type_='foreignkey')
    op.create_foreign_key(None, 'plan_items', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('reading_activities_user_id_fkey'), 'reading_activities', type_='foreignkey')
    op.create_foreign_key(None, 'reading_activities', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('recommendation_feedback_user_id_fkey'), 'recommendation_feedback', type_='foreignkey')
    op.create_foreign_key(None, 'recommendation_feedback', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('recommendations_user_id_fkey'), 'recommendations', type_='foreignkey')
    op.create_foreign_key(None, 'recommendations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('reconciliation_logs_user_id_fkey'), 'reconciliation_logs', type_='foreignkey')
    op.create_foreign_key(None, 'reconciliation_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('roadmap_nodes_user_id_fkey'), 'roadmap_nodes', type_='foreignkey')
    op.create_foreign_key(None, 'roadmap_nodes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('roadmap_plan_events_user_id_fkey'), 'roadmap_plan_events', type_='foreignkey')
    op.create_foreign_key(None, 'roadmap_plan_events', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('roadmaps_user_id_fkey'), 'roadmaps', type_='foreignkey')
    op.create_foreign_key(None, 'roadmaps', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('seteuk_uploads_user_id_fkey'), 'seteuk_uploads', type_='foreignkey')
    op.create_foreign_key(None, 'seteuk_uploads', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('student_interests_user_id_fkey'), 'student_interests', type_='foreignkey')
    op.create_foreign_key(None, 'student_interests', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('usage_events_user_id_fkey'), 'usage_events', type_='foreignkey')
    op.create_foreign_key(None, 'usage_events', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('google_id', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('withdrawal_requested_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'users', ['google_id'])
    op.drop_constraint(op.f('volunteer_records_user_id_fkey'), 'volunteer_records', type_='foreignkey')
    op.create_foreign_key(None, 'volunteer_records', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'volunteer_records', type_='foreignkey')
    op.create_foreign_key(op.f('volunteer_records_user_id_fkey'), 'volunteer_records', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'withdrawal_requested_at')
    op.drop_column('users', 'google_id')
    op.drop_column('users', 'email_verified_at')
    op.drop_constraint(None, 'usage_events', type_='foreignkey')
    op.create_foreign_key(op.f('usage_events_user_id_fkey'), 'usage_events', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'student_interests', type_='foreignkey')
    op.create_foreign_key(op.f('student_interests_user_id_fkey'), 'student_interests', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'seteuk_uploads', type_='foreignkey')
    op.create_foreign_key(op.f('seteuk_uploads_user_id_fkey'), 'seteuk_uploads', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'roadmaps', type_='foreignkey')
    op.create_foreign_key(op.f('roadmaps_user_id_fkey'), 'roadmaps', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'roadmap_plan_events', type_='foreignkey')
    op.create_foreign_key(op.f('roadmap_plan_events_user_id_fkey'), 'roadmap_plan_events', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'roadmap_nodes', type_='foreignkey')
    op.create_foreign_key(op.f('roadmap_nodes_user_id_fkey'), 'roadmap_nodes', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'reconciliation_logs', type_='foreignkey')
    op.create_foreign_key(op.f('reconciliation_logs_user_id_fkey'), 'reconciliation_logs', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'recommendations', type_='foreignkey')
    op.create_foreign_key(op.f('recommendations_user_id_fkey'), 'recommendations', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'recommendation_feedback', type_='foreignkey')
    op.create_foreign_key(op.f('recommendation_feedback_user_id_fkey'), 'recommendation_feedback', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'reading_activities', type_='foreignkey')
    op.create_foreign_key(op.f('reading_activities_user_id_fkey'), 'reading_activities', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'plan_items', type_='foreignkey')
    op.create_foreign_key(op.f('plan_items_user_id_fkey'), 'plan_items', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'diagnoses', type_='foreignkey')
    op.create_foreign_key(op.f('diagnoses_user_id_fkey'), 'diagnoses', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key(op.f('conversations_user_id_fkey'), 'conversations', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'consultation_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('consultation_sessions_user_id_fkey'), 'consultation_sessions', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'awards', type_='foreignkey')
    op.create_foreign_key(op.f('awards_user_id_fkey'), 'awards', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.create_foreign_key(op.f('attendance_user_id_fkey'), 'attendance', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'activity_threads', type_='foreignkey')
    op.create_foreign_key(op.f('activity_threads_user_id_fkey'), 'activity_threads', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'activity_reviews', type_='foreignkey')
    op.create_foreign_key(op.f('activity_reviews_user_id_fkey'), 'activity_reviews', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'activity_attachments', type_='foreignkey')
    op.create_foreign_key(op.f('activity_attachments_user_id_fkey'), 'activity_attachments', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.create_foreign_key(op.f('activities_user_id_fkey'), 'activities', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'academic_performance', type_='foreignkey')
    op.create_foreign_key(op.f('academic_performance_user_id_fkey'), 'academic_performance', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_user_id'), table_name='email_verification_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_token_hash'), table_name='email_verification_tokens')
    op.drop_table('email_verification_tokens')
    # ### end Alembic commands ###
