"""drop diagnoses.fit_score

Revision ID: acee8bdbf5c5
Revises: 2c28ba5a96d5
Create Date: 2026-09-01 00:05:09.029128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acee8bdbf5c5'
down_revision: Union[str, Sequence[str], None] = '2c28ba5a96d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diagnoses', 'fit_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagnoses', sa.Column('fit_score', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
