"""add source_upload_id to seteuk domain tables

Revision ID: ae70a0089675
Revises: b755f7f1d034
Create Date: 2026-08-26 16:57:29.703840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae70a0089675'
down_revision: Union[str, Sequence[str], None] = 'b755f7f1d034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academic_performance', sa.Column('source_upload_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_academic_performance_source_upload_id'), 'academic_performance', ['source_upload_id'], unique=False)
    op.create_foreign_key(None, 'academic_performance', 'seteuk_uploads', ['source_upload_id'], ['id'], ondelete='SET NULL')
    op.add_column('activities', sa.Column('source_upload_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_activities_source_upload_id'), 'activities', ['source_upload_id'], unique=False)
    op.create_foreign_key(None, 'activities', 'seteuk_uploads', ['source_upload_id'], ['id'], ondelete='SET NULL')
    op.add_column('attendance', sa.Column('source_upload_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_attendance_source_upload_id'), 'attendance', ['source_upload_id'], unique=False)
    op.create_foreign_key(None, 'attendance', 'seteuk_uploads', ['source_upload_id'], ['id'], ondelete='SET NULL')
    op.add_column('awards', sa.Column('source_upload_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_awards_source_upload_id'), 'awards', ['source_upload_id'], unique=False)
    op.create_foreign_key(None, 'awards', 'seteuk_uploads', ['source_upload_id'], ['id'], ondelete='SET NULL')
    op.add_column('reading_activities', sa.Column('source_upload_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_reading_activities_source_upload_id'), 'reading_activities', ['source_upload_id'], unique=False)
    op.create_foreign_key(None, 'reading_activities', 'seteuk_uploads', ['source_upload_id'], ['id'], ondelete='SET NULL')
    op.add_column('volunteer_records', sa.Column('source_upload_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_volunteer_records_source_upload_id'), 'volunteer_records', ['source_upload_id'], unique=False)
    op.create_foreign_key(None, 'volunteer_records', 'seteuk_uploads', ['source_upload_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'volunteer_records', type_='foreignkey')
    op.drop_index(op.f('ix_volunteer_records_source_upload_id'), table_name='volunteer_records')
    op.drop_column('volunteer_records', 'source_upload_id')
    op.drop_constraint(None, 'reading_activities', type_='foreignkey')
    op.drop_index(op.f('ix_reading_activities_source_upload_id'), table_name='reading_activities')
    op.drop_column('reading_activities', 'source_upload_id')
    op.drop_constraint(None, 'awards', type_='foreignkey')
    op.drop_index(op.f('ix_awards_source_upload_id'), table_name='awards')
    op.drop_column('awards', 'source_upload_id')
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.drop_index(op.f('ix_attendance_source_upload_id'), table_name='attendance')
    op.drop_column('attendance', 'source_upload_id')
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.drop_index(op.f('ix_activities_source_upload_id'), table_name='activities')
    op.drop_column('activities', 'source_upload_id')
    op.drop_constraint(None, 'academic_performance', type_='foreignkey')
    op.drop_index(op.f('ix_academic_performance_source_upload_id'), table_name='academic_performance')
    op.drop_column('academic_performance', 'source_upload_id')
    # ### end Alembic commands ###
