"""drop seteuk_uploads.file_id

Revision ID: b755f7f1d034
Revises: 4660c15ab402
Create Date: 2026-08-26 16:24:34.688527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b755f7f1d034'
down_revision: Union[str, Sequence[str], None] = '4660c15ab402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seteuk_uploads', 'file_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seteuk_uploads', sa.Column('file_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
