"""add diagnoses.narrative_report

Revision ID: b9c56ced77ac
Revises: f0a24904d2e3
Create Date: 2026-08-30 11:56:09.042474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9c56ced77ac'
down_revision: Union[str, Sequence[str], None] = 'f0a24904d2e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagnoses', sa.Column('narrative_report', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diagnoses', 'narrative_report')
    # ### end Alembic commands ###
