"""activities: reflection + source_plan_event_id

Revision ID: c91cd010da60
Revises: f1e8bc7b1770
Create Date: 2026-09-04 21:17:37.136141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c91cd010da60'
down_revision: Union[str, Sequence[str], None] = 'f1e8bc7b1770'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('reflection', sa.Text(), nullable=True))
    op.add_column('activities', sa.Column('source_plan_event_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'fk_activities_source_plan_event_id',
        'activities',
        'roadmap_plan_events',
        ['source_plan_event_id'],
        ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_activities_source_plan_event_id', 'activities', type_='foreignkey')
    op.drop_column('activities', 'source_plan_event_id')
    op.drop_column('activities', 'reflection')
    # ### end Alembic commands ###
