"""academic performance note

Revision ID: ef28cddc0af0
Revises: 1a5d54f88842
Create Date: 2026-09-04 04:21:09.639751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef28cddc0af0'
down_revision: Union[str, Sequence[str], None] = '1a5d54f88842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academic_performance', sa.Column('note', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('academic_performance', 'note')
    # ### end Alembic commands ###
