"""activity performed on

Revision ID: f8c221cfeae6
Revises: 88b5b06922e6
Create Date: 2026-09-04 12:11:45.791202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8c221cfeae6'
down_revision: Union[str, Sequence[str], None] = '88b5b06922e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('performed_on', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'performed_on')
    # ### end Alembic commands ###
